version: '3.8'

services:
  lavalink:
    container_name: vocard-lavalink
    image: ghcr.io/lavalink-devs/lavalink:latest
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx1G -Djava.net.preferIPv4Stack=true
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD:-youshallnotpass}
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
    networks:
      - vocard
    ports:
      - "${LAVALINK_PORT:-2333}:2333"

  spotify-tokener:
    image: ghcr.io/topi314/spotify-tokener:master
    container_name: vocard-spotify-tokener
    restart: unless-stopped
    environment:
      - SPOTIFY_TOKENER_ADDR=0.0.0.0:49152
    networks:
      - vocard
    ports:
      - "${SPOTIFY_TOKENER_PORT:-49152}:49152"

  vocard-db:
    container_name: vocard-db
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - ./data/mongo/db:/data/db
      - ./data/mongo/conf:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS:-adminpassword123}
    networks:
      - vocard

  vocard:
    container_name: vocard-bot
    image: ghcr.io/chocomeow/vocard:latest
    restart: unless-stopped
    volumes:
      - ./vocard/settings.json:/app/settings.json
    networks:
      - vocard
    depends_on:
      - lavalink
      - vocard-db

  vocard-dashboard:
    container_name: vocard-dashboard
    image: ghcr.io/chocomeow/vocard-dashboard:latest
    restart: unless-stopped
    ports:
      - "${DASHBOARD_PORT:-8880}:8080"
    volumes:
      - ./dashboard/settings.json:/app/settings.json
    networks:
      - vocard
    depends_on:
      - vocard

networks:
  vocard:
    driver: bridge
